### ISSUE TITLE
Suggestion: instanciate the Levenshtein index with maxEdits and minNchar directly in the TermDetector class

### ISSUE THREAD

**Issue by gozat** [scossin/IAMsystem#2]
At the present time the `.addLevenshteinIndex` in the class `TermDetector` only implements the defaults versio of the Levenshtein synonyms checking.

I propose to add the following polymorphic method to the `TermDetector` class, in
IAMsystem/src/main/java/fr/erias/IAMsystem/detect/TermDetector.java

```java
	/**
	 * Create a Lucene index
	 * @param terminology {@link Terminology}
	 * @param maxEdits 
	 * @param minNchar
	 * @throws IOException if 
	 */
	public void addLevenshteinIndex(Terminology terminology, int maxEdits, int minNchar) throws IOException {
		IndexBigramLucene.IndexLuceneUniqueTokensBigram(terminology, this.tokenizerNormalizer); // create the index ; do it only once
		LevenshteinTypoLucene levenshteinTypoLucene = new LevenshteinTypoLucene(); // open the index
                levenshteinTypoLucene.setMaxEdits(maxEdits);
                levenshteinTypoLucene.setMinNchar(minNchar);
		this.levenshtein = levenshteinTypoLucene;
	}
```

**Comment by scossin** [comment]
I have removed LevenshteinTypoLucene and Abbreviations from the termDetector class in the new release 1.1.0 https://github.com/scossin/IAMsystem/commit/e958062eae2358c7709fb4f43e6c9ddf69412283. In the future, new classes that implements the ISynonym interface will be added and it makes no sense to add/access them from TermDetector.   

You have methods to add, set and retrieve ISynonym instances from the TermDetector class. For example, to add a LevenshteinTypoLucene instance to TermDetector, just do: 

``` java
LevenshteinTypoLucene levenshteinTypoLucene = new LevenshteinTypoLucene(); // open the index
termDetector.addSynonym(levenshteinTypoLucene); // now it handles typos
```
If you need to change the number of edits or the minimum token length:
``` java
// change minEdits:
levenshteinTypoLucene.setMaxEdits(2); // 2 insertions/deletions allowed per token
// change minChar:
levenshteinTypoLucene.setMinNchar(9); // ignore token with less than 9 characters
```
I have updated the examples.
